port: 4005
title: AlgonquinDesign.ca
email: paradia@algonquincollege.ca
description: 
baseurl: ""
url: "https://alainparadis.github.io/ad/"
twitter_username: "@algonquindesign"
github_username:  "@algonquindesign"

plugins:
  - jekyll-feed

repository: alainparadis/ad

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
